spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:security-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:username}
    password: ${DB_PAWORD:password}
    driver-class-name: org.h2.Driver
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/jwt_security_db}
#    username: ${DB_USER:username}
#    password: ${DB_PAWORD:password}
#    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/dbjwt
    #username: diagana
    #password: passer

  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
